# RB-PLPE — Naukri Dataset → Role Skill Mapping

## Imports & Paths

In [15]:
import pandas as pd
import os

RAW_PATH = r"H:\resume_project\RB-PLPE\data\raw\naukri.csv"
CLEAN_PATH = r"H:\resume_project\RB-PLPE\data\cleaned\role_skill_mapping.csv"

os.makedirs(r"H:\resume_project\full_stack\chai-code\data\cleaned", exist_ok=True)

print("Input :", RAW_PATH)
print("Output:", CLEAN_PATH)

Input : H:\resume_project\RB-PLPE\data\raw\naukri.csv
Output: H:\resume_project\RB-PLPE\data\cleaned\role_skill_mapping.csv

## Load & Inspect

In [16]:
df = pd.read_csv(RAW_PATH)

print("Shape : ", df.shape)
print("Columns : ", df.columns.to_list())
print("\nNull counts: ")
print(df.isnull().sum())
print("\nSample Key Skills:")
print(df["Key Skills"].head(5).tolist())
df.head(3)

Shape :  (30000, 11)
Columns :  ['Uniq Id', 'Crawl Timestamp', 'Job Title', 'Job Salary', 'Job Experience Required', 'Key Skills', 'Role Category', 'Location', 'Functional Area', 'Industry', 'Role']

Null counts:
Uniq Id                       0
Crawl Timestamp               0
Job Title                   575
Job Salary                   50
Job Experience Required     573
Key Skills                 1271
Role Category              2305
Location                    577
Functional Area             573
Industry                    573
Role                        901
dtype: int64

Sample Key Skills:
[' Media Planning| Digital Media', ' pre sales| closing| software knowledge| clients| requirements| negotiating| client| online bidding| good communication| technology', ' Computer science| Fabrication| Quality check| Intellectual property| Electronics| Support services| Research| Management| Human resource management| Research Executive', ' Technical Support', ' manual testing| test engineering| test cases| web testing| web technologies']

,Uniq Id,Crawl Timestamp,Job Title,Job Salary,Job Experience Required,Key Skills,Role Category,Location,Functional Area,Industry,Role
0,9be62c49a0b7ebe982a4af1edaa7bc5f,2019-07-05 01:46:07 +0000,Digital Media Planner,Not Disclosed by Recruiter,5 - 10 yrs,Media Planning| Digital Media,Advertising,Mumbai,"Marketing , Advertising , MR , PR , Media Plan...","Advertising, PR, MR, Event Management",Media Planning Executive/Manager
1,3c52d436e39f596b22519da2612f6a56,2019-07-06 08:04:50 +0000,Online Bidding Executive,Not Disclosed by Recruiter,2 - 5 yrs,pre sales| closing| software knowledge| clien...,Retail Sales,"Pune,Pune","Sales , Retail , Business Development","IT-Software, Software Services",Sales Executive/Officer
2,ffad8a2396c60be2bf6d0e2ff47c58d4,2019-08-05 15:50:44 +0000,Trainee Research/ Research Executive- Hi- Tec...,Not Disclosed by Recruiter,0 - 1 yrs,Computer science| Fabrication| Quality check|...,R&D,Gurgaon,"Engineering Design , R&D","Recruitment, Staffing",R&D Executive

## Extract Important Columns

In [17]:
# Only Job Title and Key Skills are needed
df = df[["Job Title", "Key Skills"]].copy()

df = df.dropna(subset= ["Job Title" , "Key Skills"])

df["Job Title"] = df["Job Title"].str.strip()
df["Key Skills"] = df["Key Skills"].str.strip()

print(f"Rows after dropping nulls: {len(df)}")
df.head(3)

Rows after dropping nulls: 28371

,Job Title,Key Skills
0,Digital Media Planner,Media Planning| Digital Media
1,Online Bidding Executive,pre sales| closing| software knowledge| client...
2,Trainee Research/ Research Executive- Hi- Tech...,Computer science| Fabrication| Quality check| ...

## Filtering the IT Job form the Titles

In [18]:
# Keywords covering ALL IT job roles
it_keywords = [
    # Data roles
    "data scientist", "data analyst", "data engineer", "data science",
    "business intelligence", "bi analyst", "bi developer", "analytics",
    # ML / AI
    "machine learning", "ml engineer", "deep learning",
    "ai engineer", "nlp", "natural language", "computer vision",
    # Software development
    "software engineer", "software developer", "software development",
    "python developer", "java developer", "php developer",
    "dot net developer", ".net developer", "asp.net",
    "node developer", "react developer", "angular developer",
    "wordpress developer", "magento developer", "salesforce developer",
    # Web
    "frontend developer", "front end developer", "front-end developer",
    "backend developer", "back end developer", "back-end developer",
    "full stack developer", "full-stack developer", "web developer",
    "ui developer", "web designer", "ui ux", "ui/ux",
    # Mobile
    "android developer", "ios developer", "mobile application",
    "mobile developer", "flutter developer", "react native",
    # DevOps / Cloud
    "devops", "cloud engineer", "aws engineer", "azure engineer",
    "site reliability", "sre", "infrastructure engineer",
    # Security
    "cybersecurity", "security analyst", "information security",
    "network security", "ethical hacker", "penetration tester",
    # Database
    "database administrator", "dba", "database engineer",
    # QA / Testing
    "qa engineer", "quality assurance", "test engineer",
    "automation test", "manual testing", "software tester",
    # Network / Systems
    "network engineer", "system administrator", "sysadmin",
    "network administrator", "it support", "technical support",
    # Other IT
    "business analyst", "solution architect", "technical architect",
    "tech lead", "technical lead", "scrum master", "project manager",
    "embedded", "blockchain", "game developer",
]

pattern = "|".join(it_keywords)
df = df[df["Job Title"].str.lower().str.contains(pattern, na = False)].copy()

In [19]:
print(f"IT relevant rows: {len(df)}")
print("\nTop 30 Job Titles:")
print(df["Job Title"].value_counts().head(30))

IT relevant rows: 5325

Top 30 Job Titles:
Job Title
PHP Developer                    117
Java Developer                    82
Software Engineer                 80
Android Developer                 77
Business Analyst                  67
Senior Software Engineer          63
Web Designer                      59
Dot Net Developer                 59
Software Developer                47
Project Manager                   45
Full Stack Developer              32
Python Developer                  31
Web Developer                     31
Sr. Software Engineer             30
UI Developer                      29
iOS Developer                     25
IOS Developer                     25
Data Scientist                    25
Senior Java Developer             24
Magento Developer                 20
Devops Engineer                   19
Technical Lead                    18
Front End Developer               17
Salesforce Developer              17
QA Engineer                       16
Software Development Engineer     13
Network Engineer                  13
Senior PHP Developer              13
Data Engineer                     13
Backend Developer                 13
Name: count, dtype: int64

## Mapping of Standard IT Roles

In [20]:
# Maps every job title variation → one clean standard role name
# These role names must match exactly what is in your Streamlit dropdown

def map_to_standard_role(title):
    t = title.lower()

    # ── Data & AI ──
    if any(x in t for x in ["data scientist", "data science"]):
        return "Data Scientist"
    elif any(x in t for x in ["machine learning", "ml engineer", "deep learning", "ai engineer", "artificial intelligence"]):
        return "Machine Learning Engineer"
    elif any(x in t for x in ["data analyst", "analytics analyst"]):
        return "Data Analyst"
    elif "data engineer" in t:
        return "Data Engineer"
    elif any(x in t for x in ["business intelligence", "bi analyst", "bi developer"]):
        return "Business Intelligence Analyst"
    elif any(x in t for x in ["nlp", "natural language"]):
        return "NLP Engineer"
    elif any(x in t for x in ["computer vision", "cv engineer"]):
        return "Computer Vision Engineer"

    # ── Web & Software ──
    elif any(x in t for x in ["full stack", "full-stack"]):
        return "Full Stack Developer"
    elif any(x in t for x in ["frontend", "front end", "front-end", "ui developer", "react developer", "angular developer", "vue developer"]):
        return "Frontend Developer"
    elif any(x in t for x in ["backend", "back end", "back-end", "node developer", "django developer", "flask developer"]):
        return "Backend Developer"
    elif any(x in t for x in ["software engineer", "software developer", "software development", "python developer", "java developer",
                               "php developer", ".net developer", "dot net", "asp.net", "wordpress developer",
                               "magento developer", "salesforce developer"]):
        return "Software Engineer"

    # ── Mobile ──
    elif any(x in t for x in ["android developer", "android engineer"]):
        return "Android Developer"
    elif any(x in t for x in ["ios developer", "ios engineer", "swift developer"]):
        return "iOS Developer"
    elif any(x in t for x in ["mobile application", "flutter", "react native", "mobile developer"]):
        return "Mobile App Developer"

    # ── DevOps / Cloud ──
    elif any(x in t for x in ["devops", "site reliability", "sre"]):
        return "DevOps Engineer"
    elif any(x in t for x in ["cloud engineer", "aws engineer", "azure engineer", "gcp engineer", "infrastructure engineer"]):
        return "Cloud Engineer"

    # ── Security ──
    elif any(x in t for x in ["cybersecurity", "security analyst", "information security", "network security", "ethical hacker", "penetration"]):
        return "Cybersecurity Analyst"

    # ── Database ──
    elif any(x in t for x in ["database administrator", "dba", "database engineer"]):
        return "Database Administrator"

    # ── QA ──
    elif any(x in t for x in ["qa engineer", "quality assurance", "test engineer", "automation test", "software tester"]):
        return "QA Engineer"

    # ── Network / Systems ──
    elif any(x in t for x in ["network engineer", "network administrator"]):
        return "Network Engineer"
    elif any(x in t for x in ["system administrator", "sysadmin", "it support", "technical support"]):
        return "System Administrator"

    # ── UI/UX ──
    elif any(x in t for x in ["ui ux", "ui/ux", "ux designer", "web designer", "product designer"]):
        return "UI/UX Designer"

    # ── Other IT ──
    elif any(x in t for x in ["business analyst"]):
        return "Business Analyst"
    elif any(x in t for x in ["solution architect", "technical architect"]):
        return "Solutions Architect"
    elif any(x in t for x in ["tech lead", "technical lead"]):
        return "Tech Lead"
    elif any(x in t for x in ["embedded"]):
        return "Embedded Systems Engineer"
    elif "blockchain" in t:
        return "Blockchain Developer"
    else:
        return None

In [21]:
df["role_name"] = df["Job Title"].apply(map_to_standard_role)
df = df.dropna(subset=["role_name"])

print(f"Rows after role mapping: {len(df)}")
print("\nRole distribution:")
print(df["role_name"].value_counts())

Rows after role mapping: 4845

Role distribution:
role_name
Software Engineer                2124
QA Engineer                       264
Frontend Developer                260
System Administrator              244
Full Stack Developer              195
Business Analyst                  180
UI/UX Designer                    173
Android Developer                 158
Tech Lead                         157
DevOps Engineer                   152
iOS Developer                     122
Solutions Architect               102
Data Scientist                     96
Database Administrator             83
Backend Developer                  75
Embedded Systems Engineer          69
Mobile App Developer               65
Cybersecurity Analyst              54
Business Intelligence Analyst      53
Data Analyst                       53
Network Engineer                   51
Data Engineer                      46
Machine Learning Engineer          34
Cloud Engineer                     18
Blockchain Developer               12
NLP Engineer                        4
Computer Vision Engineer            1
Name: count, dtype: int64

## Clean & Normalize Skill Names

In [22]:
def clean_skills(skill_string):
    skills = skill_string.split("|")
    skills  = [s.strip().lower() for s in skills if s.strip()]
    return skills

df["skills_list"] = df["Key Skills"].apply(clean_skills)
print(df["skills_list"].head(2))

3                                  [technical support]
4    [manual testing, test engineering, test cases,...
Name: skills_list, dtype: object

In [23]:
# Normalize abbreviations to full names
synonym_map = {
    "ml"          : "machine learning",
    "ai"          : "artificial intelligence",
    "dl"          : "deep learning",
    "nlp"         : "natural language processing",
    "cv"          : "computer vision",
    "dbms"        : "database management",
    "ds"          : "data science",
    "stats"       : "statistics",
    "tf"          : "tensorflow",
    "sklearn"     : "scikit-learn",
    "js"          : "javascript",
    "ts"          : "typescript",
    "k8s"         : "kubernetes",
    "oop"         : "object oriented programming",
    "oops"        : "object oriented programming",
    "dsa"         : "data structures and algorithms",
    "ci/cd"       : "ci cd pipelines",
    "restapi"     : "rest api",
    "rest apis"   : "rest api",
}

def apply_synonyms(skills):
    return [synonym_map.get(s, s) for s in skills]

df["skills_list"] = df["skills_list"].apply(apply_synonyms)

print("Sample cleaned skills:")
for row in df["skills_list"].head(5).tolist():
    print(" ", row)

Sample cleaned skills:
  ['technical support']
  ['manual testing', 'test engineering', 'test cases', 'web testing', 'web technologies']
  ['tfs', 'azure', 'git', 'vsts', 'docker', 'dynatrace', 'splunk', 'aws']
  ['technical support', 'support services', 'application support', 'communication skills', 'voice based process', 'semi voice', 'semi voice process']
  ['copyright', 'email', 'jquery', 'xml', 'javascript', 'cakephp', 'customer service', 'open source', 'facebook', 'css3']

## Calculate Importance Score
`importance_score = skill_count / total_jobs_for_that_role`

In [26]:
df.head(3)

,Job Title,Key Skills,role_name,skills_list
3,Technical Support,Technical Support,System Administrator,[technical support]
4,Software Test Engineer -hyderabad,manual testing| test engineering| test cases| ...,QA Engineer,"[manual testing, test engineering, test cases,..."
7,Opportunity For Azure Devops Architect For Hyd...,TFS| Azure| Git| VSTS| Docker| DynaTrace| Splu...,DevOps Engineer,"[tfs, azure, git, vsts, docker, dynatrace, spl..."

In [29]:
# Step 1: Total jobs per role
total_jobs_per_role = df.groupby("role_name").size().reset_index(name = "total_jobs")
print("Total jobs per role:")
print(total_jobs_per_role.to_string(index = False))

Total jobs per role:
                    role_name  total_jobs
            Android Developer         158
            Backend Developer          75
         Blockchain Developer          12
             Business Analyst         180
Business Intelligence Analyst          53
               Cloud Engineer          18
     Computer Vision Engineer           1
        Cybersecurity Analyst          54
                 Data Analyst          53
                Data Engineer          46
               Data Scientist          96
       Database Administrator          83
              DevOps Engineer         152
    Embedded Systems Engineer          69
           Frontend Developer         260
         Full Stack Developer         195
    Machine Learning Engineer          34
         Mobile App Developer          65
                 NLP Engineer           4
             Network Engineer          51
                  QA Engineer         264
            Software Engineer        2124
          Solutions Architect         102
         System Administrator         244
                    Tech Lead         157
               UI/UX Designer         173
                iOS Developer         122

In [32]:
# Step 2: Explode — one row per skill per job
df_exploded = df[["role_name", "skills_list"]].explode("skills_list")
df_exploded = df_exploded.rename(columns={"skills_list": "required_skill"})
df_exploded = df_exploded[df_exploded["required_skill"].str.len() > 2]
print(df_exploded)

                  role_name     required_skill
3      System Administrator  technical support
4               QA Engineer     manual testing
4               QA Engineer   test engineering
4               QA Engineer         test cases
4               QA Engineer        web testing
...                     ...                ...
29991     Software Engineer             vb.net
29991     Software Engineer                asp
29991     Software Engineer                css
29991     Software Engineer                xml
29991     Software Engineer               .net

[42871 rows x 2 columns]

In [33]:
# Step 3: Count skill frequency per role
skill_counts = df_exploded.groupby(
    ["role_name", "required_skill"]
).size().reset_index(name="skill_count")
print(skill_counts)

              role_name     required_skill  skill_count
0     Android Developer               .net            7
1     Android Developer          academics            1
2     Android Developer      advanced java            2
3     Android Developer              agile            2
4     Android Developer  agile development            1
...                 ...                ...          ...
9888      iOS Developer            xamarin            1
9889      iOS Developer              xcode           19
9890      iOS Developer              xhtml            1
9891      iOS Developer                xml           27
9892      iOS Developer               zend            1

[9893 rows x 3 columns]

In [35]:
# Step 4: Merge with total jobs
result = skill_counts.merge(total_jobs_per_role, on="role_name")
print(result)

              role_name     required_skill  skill_count  total_jobs
0     Android Developer               .net            7         158
1     Android Developer          academics            1         158
2     Android Developer      advanced java            2         158
3     Android Developer              agile            2         158
4     Android Developer  agile development            1         158
...                 ...                ...          ...         ...
9888      iOS Developer            xamarin            1         122
9889      iOS Developer              xcode           19         122
9890      iOS Developer              xhtml            1         122
9891      iOS Developer                xml           27         122
9892      iOS Developer               zend            1         122

[9893 rows x 4 columns]

In [36]:
# Step 5: Calculate importance score
result["importance_score"] = (result["skill_count"] / result["total_jobs"]).round(2)

print(result["importance_score"])

0       0.04
1       0.01
2       0.01
3       0.01
4       0.01
        ...
9888    0.01
9889    0.16
9890    0.01
9891    0.22
9892    0.01
Name: importance_score, Length: 9893, dtype: float64

In [37]:
# Step 6: Keep skills appearing in at least 5% of jobs for that role
result = result[result["importance_score"] >= 0.05]
print(result)

              role_name                   required_skill  skill_count  \
12    Android Developer                          android           90
14    Android Developer  android application development           11
16    Android Developer              android development           27
18    Android Developer                      android sdk           55
19    Android Developer                   android studio           21
...                 ...                              ...          ...
9879      iOS Developer                              web            9
9880      iOS Developer                     web services            8
9881      iOS Developer                 web technologies            8
9889      iOS Developer                            xcode           19
9891      iOS Developer                              xml           27

      total_jobs  importance_score
12           158              0.57
14           158              0.07
16           158              0.17
18           158              0.35
19           158              0.13
...          ...               ...
9879         122              0.07
9880         122              0.07
9881         122              0.07
9889         122              0.16
9891         122              0.22

[1108 rows x 5 columns]

In [40]:
# Step 7: Sort by role then importance descending
result = result.sort_values(
    ["role_name", "importance_score"],
    ascending=[True, False]
).reset_index(drop=True)

print(f"\nTotal role-skill pairs: {len(result)}")
print("\nSample:")
print(result.head(20).to_string(index=False))

Total role-skill pairs: 1108

Sample:
        role_name      required_skill  skill_count  total_jobs  importance_score
Android Developer             android           90         158              0.57
Android Developer         android sdk           55         158              0.35
Android Developer                json           43         158              0.27
Android Developer                java           34         158              0.22
Android Developer                 xml           30         158              0.19
Android Developer android development           27         158              0.17
Android Developer              design           26         158              0.16
Android Developer              sqlite           22         158              0.14
Android Developer      android studio           21         158              0.13
Android Developer         development           20         158              0.13
Android Developer          javascript           21         158              0.13
Android Developer           developer           17         158              0.11
Android Developer              mobile           17         158              0.11
Android Developer                rest           18         158              0.11
Android Developer                 sdk           17         158              0.11
Android Developer                 git           16         158              0.10
Android Developer                 sql           16         158              0.10
Android Developer    web technologies           16         158              0.10
Android Developer         application           15         158              0.09
Android Developer           core java           15         158              0.09

## Quality Check

In [41]:
final_df = result[["role_name", "required_skill", "importance_score"]].copy()

print("=" * 55)
print("FINAL DATASET REPORT")
print("=" * 55)
print(f"Total rows  : {len(final_df)}")
print(f"Total roles : {final_df['role_name'].nunique()}")
print(f"Null values : {final_df.isnull().sum().sum()}")

print("\nSkill pairs per role:")
print(final_df["role_name"].value_counts().to_string())

# Show top skills for a few key roles
for role in ["Software Engineer", "Data Scientist", "DevOps Engineer", "Frontend Developer"]:
    subset = final_df[final_df["role_name"] == role]
    if len(subset) > 0:
        print(f"\nTop 8 skills — {role}:")
        print(subset.head(8).to_string(index=False))

final_df.head(10)

=======================================================
FINAL DATASET REPORT
=======================================================
Total rows  : 1108
Total roles : 27
Null values : 0

Skill pairs per role:
role_name
Cloud Engineer                   111
Blockchain Developer              78
Mobile App Developer              54
iOS Developer                     53
Backend Developer                 52
Database Administrator            48
Full Stack Developer              47
System Administrator              46
Data Engineer                     42
Software Engineer                 42
DevOps Engineer                   42
Android Developer                 39
UI/UX Designer                    39
Embedded Systems Engineer         38
QA Engineer                       36
Frontend Developer                36
Data Scientist                    35
Network Engineer                  35
Cybersecurity Analyst             34
Solutions Architect               33
Machine Learning Engineer         32
Tech Lead                         29
Business Intelligence Analyst     29
NLP Engineer                      27
Data Analyst                      24
Business Analyst                  17
Computer Vision Engineer          10

Top 8 skills — Software Engineer:
        role_name required_skill  importance_score
Software Engineer     javascript              0.31
Software Engineer         jquery              0.21
Software Engineer           html              0.18
Software Engineer           java              0.18
Software Engineer            sql              0.18
Software Engineer          mysql              0.17
Software Engineer            mvc              0.15
Software Engineer            php              0.15

Top 8 skills — Data Scientist:
     role_name              required_skill  importance_score
Data Scientist                      python              0.65
Data Scientist            machine learning              0.61
Data Scientist                data science              0.39
Data Scientist                         sql              0.32
Data Scientist                 data mining              0.23
Data Scientist                    big data              0.19
Data Scientist               deep learning              0.19
Data Scientist natural language processing              0.16

Top 8 skills — DevOps Engineer:
      role_name required_skill  importance_score
DevOps Engineer         devops              0.49
DevOps Engineer         python              0.34
DevOps Engineer        jenkins              0.32
DevOps Engineer          linux              0.32
DevOps Engineer            aws              0.28
DevOps Engineer        ansible              0.21
DevOps Engineer         docker              0.21
DevOps Engineer            git              0.20

Top 8 skills — Frontend Developer:
         role_name required_skill  importance_score
Frontend Developer     javascript              0.71
Frontend Developer           html              0.46
Frontend Developer            css              0.40
Frontend Developer      front end              0.40
Frontend Developer         jquery              0.38
Frontend Developer          html5              0.30
Frontend Developer      angularjs              0.24
Frontend Developer           css3              0.23

           role_name       required_skill  importance_score
0  Android Developer              android              0.57
1  Android Developer          android sdk              0.35
2  Android Developer                 json              0.27
3  Android Developer                 java              0.22
4  Android Developer                  xml              0.19
5  Android Developer  android development              0.17
6  Android Developer               design              0.16
7  Android Developer               sqlite              0.14
8  Android Developer       android studio              0.13
9  Android Developer          development              0.13

## Save to data/cleaned/

In [42]:
# CLEAN_PATH = r"H:\resume_project\RB-PLPE\data\cleaned\role_skill_mapping.csv"
final_df.to_csv(CLEAN_PATH, index=False)

print(f"Saved  : {CLEAN_PATH}")
print(f"Rows   : {len(final_df)}")
print(f"Columns: {final_df.columns.tolist()}")

Saved  : H:\resume_project\RB-PLPE\data\cleaned\role_skill_mapping.csv
Rows   : 1108
Columns: ['role_name', 'required_skill', 'importance_score']

In [43]:
print("\nDone! Ready to load into Neo4j.")

Done! Ready to load into Neo4j.